"use client";

import { useState } from "react";
import results from "@/lib/results.json";
import { FINDINGS } from "@/lib/content";
import OperatingCurve from "./OperatingCurve";

/**
 * Measured results.
 *
 * Every number here is read from `lib/results.json`, which is generated by
 * `scripts/export_results.py` from the run directories on disk — nothing is
 * typed into this component. If a benchmark has not been run it is absent from
 * the file and this pane says so, rather than showing a plausible placeholder.
 */

interface Stat { mean: number | null; std: number | null }
interface Row {
  variant: string; label: string; role: string; runs: number;
  num_false_alarms?: number | null;
  num_falls?: number | null;
  num_warned?: number | null;
  negative_hours?: number | null;
  [metric: string]: Stat | string | number | null | undefined;
}
interface Benchmark {
  id: string; name: string; kind: string; caveat: string;
  split?: string; seeds: number[];
  dataset: { clips: number; falls: number; adls: number; subjects: number; minutes: number } | null;
  rows: Row[];
}

const BENCHMARKS = (results.benchmarks ?? []) as unknown as Benchmark[];

function fmt(stat: Stat | undefined, digits = 3, suffix = ""): string {
  if (!stat || stat.mean === null) return "—";
  const mean = stat.mean.toFixed(digits);
  if (stat.std === null || stat.std === 0) return `${mean}${suffix}`;
  return `${mean} ± ${stat.std.toFixed(digits)}${suffix}`;
}

const COLUMNS: { key: string; head: string; digits: number; suffix?: string; hint: string }[] = [
  { key: "recall", head: "Recall", digits: 3, hint: "falls warned before impact — primary metric" },
  { key: "mean_lead_time", head: "Lead time", digits: 3, suffix: " s", hint: "over correctly warned falls only" },
  { key: "false_alarms_per_hour", head: "FA / h", digits: 2, hint: "per hour of genuinely normal time" },
  { key: "specificity", head: "Specificity", digits: 3, hint: "ADL clips with no trigger at all" },
  { key: "frame_auc", head: "Frame AUC", digits: 3, hint: "threshold-free separability" },
  { key: "faith_deletion_gap", head: "Del. gap", digits: 3, hint: "vs random joint order; positive is faithful" },
  { key: "faith_insertion_gap", head: "Ins. gap", digits: 3, hint: "vs random joint order; positive is faithful" },
];

function Table({ benchmark }: { benchmark: Benchmark }) {
  return (
    <div className="table-scroll">
      <table className="data">
        <thead>
          <tr>
            <th>Variant</th>
            {COLUMNS.map((c) => (
              <th key={c.key} className="num" title={c.hint}>{c.head}</th>
            ))}
            <th className="num" title="absolute counts — the rate above is quantised">
              Falls&nbsp;/&nbsp;FAs
            </th>
          </tr>
        </thead>
        <tbody>
          {benchmark.rows.map((row) => (
            <tr key={row.variant} className={row.role === "ours" ? "ours" : undefined}>
              <td style={{ whiteSpace: "nowrap" }}>
                {row.label}
                {row.role === "baseline" && (
                  <span className="chip" style={{ marginLeft: 8, fontSize: 10 }}>baseline</span>
                )}
              </td>
              {COLUMNS.map((c) => (
                <td key={c.key} className="num">
                  {fmt(row[c.key] as Stat, c.digits, c.suffix)}
                </td>
              ))}
              <td className="num dim" title="falls warned of falls tested / total false triggers">
                {row.num_warned ?? "—"}/{row.num_falls ?? "—"} · {row.num_false_alarms ?? "—"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function ResultsPane() {
  const [active, setActive] = useState(0);
  const benchmark = BENCHMARKS[active];

  return (
    <section id="results" className="pane">
      <span className="eyebrow">Results</span>
      <h2 className="pane-title">What the experiments found</h2>
      <p className="pane-lede">
        The headline is negative: <b>the novel component of this project did not work.</b> On
        real falls the pre-impact objective cost recall and lead time rather than trading one
        for the other, and the reproduced baseline beat it. That is stated first because a
        results page that leads with its successes and files its central failure under
        &ldquo;limitations&rdquo; is not reporting, it is marketing.
      </p>

      <div className="stack" style={{ marginBottom: 30 }}>
        {FINDINGS.map((f) => {
          const colour =
            f.verdict === "negative" ? "var(--impact)"
              : f.verdict === "positive" ? "var(--calm)" : "var(--watch)";
          return (
            <div key={f.title} className="glass pad" style={{ borderLeft: `3px solid ${colour}` }}>
              <div style={{ display: "flex", gap: 10, alignItems: "baseline",
                            flexWrap: "wrap", marginBottom: 6 }}>
                <span className="chip mono" style={{ color: colour, borderColor: colour }}>
                  {f.verdict === "negative" ? "does not work"
                    : f.verdict === "positive" ? "works" : "inconclusive"}
                </span>
                <h3 className="card-title" style={{ margin: 0 }}>{f.title}</h3>
                <span className="readout" style={{ marginLeft: "auto" }}>{f.rq}</span>
              </div>
              <p className="card-sub" style={{ margin: 0 }}>{f.body}</p>
            </div>
          );
        })}
      </div>

      <h2 className="pane-title">The tables</h2>
      <p className="pane-lede">
        Every cell is a mean ± standard deviation, never a single run. The operating point
        (τ, k) was chosen on a validation split under a false-alarm budget and frozen before
        the test set was touched. On UR Fall the grid sweeps all five folds, so every one of
        the 30 real falls is tested exactly once.
      </p>

      {BENCHMARKS.length === 0 ? (
        <div className="glass pad">
          <div className="empty">
            No benchmark has been run yet.
            <div className="mono" style={{ marginTop: 10, fontSize: 12 }}>
              python scripts/run_ablations.py --seeds 0 1 2
              <br />
              python scripts/export_results.py
            </div>
          </div>
        </div>
      ) : (
        <>
          {BENCHMARKS.length > 1 && (
            <div style={{ display: "flex", gap: 7, marginBottom: 14, flexWrap: "wrap" }}>
              {BENCHMARKS.map((b, i) => (
                <button key={b.id} className={`btn${i === active ? " primary" : ""}`}
                        onClick={() => setActive(i)}>
                  {b.name}
                  <span style={{ opacity: 0.7, fontSize: 11, marginLeft: 4 }}>
                    {b.kind === "real" ? "real video" : "synthetic"}
                  </span>
                </button>
              ))}
            </div>
          )}

          <div className="glass pad">
            <div style={{ display: "flex", gap: 14, flexWrap: "wrap",
                          alignItems: "baseline", marginBottom: 12 }}>
              <h3 className="card-title" style={{ margin: 0 }}>{benchmark.name}</h3>
              <span className={`chip`} style={{
                borderColor: benchmark.kind === "real" ? "rgba(78,201,165,.4)" : "var(--glass-edge)",
                color: benchmark.kind === "real" ? "var(--calm)" : "var(--text-3)",
              }}>
                {benchmark.kind === "real" ? "real video" : "synthetic fixture"}
              </span>
              {benchmark.dataset && (
                <span className="readout">
                  {benchmark.dataset.clips} clips · {benchmark.dataset.falls} falls ·{" "}
                  {benchmark.dataset.adls} ADL · {benchmark.dataset.subjects} groups ·{" "}
                  {benchmark.dataset.minutes} min
                </span>
              )}
            </div>

            <Table benchmark={benchmark} />

            <p className="card-sub" style={{ marginTop: 14, marginBottom: 0 }}>
              {benchmark.split && <><b style={{ color: "var(--text-2)" }}>Split:</b> {benchmark.split}. </>}
              <b style={{ color: "var(--text-2)" }}>Seeds:</b>{" "}
              {benchmark.seeds.length ? benchmark.seeds.join(", ") : "—"}.
            </p>
          </div>

          <div className="notice warn" style={{ marginTop: 14 }}>
            <b style={{ color: "var(--text)" }}>
              How to read this {benchmark.kind === "real" ? "benchmark" : "fixture"}:
            </b>{" "}
            {benchmark.caveat}
          </div>

          <div className="cols-3" style={{ marginTop: 16 }}>
            <div className="glass pad">
              <h3 className="card-title">Reading the lead-time column</h3>
              <p className="card-sub" style={{ marginBottom: 0 }}>
                Averaged over correctly warned falls only, so it must be read together with
                recall. A variant that warns on one easy fall out of thirty can post an excellent
                lead time; that is why recall sits in the column beside it and why both are
                reported at a fixed false-alarm budget.
              </p>
            </div>
            <div className="glass pad">
              <h3 className="card-title">Reading the faithfulness gaps</h3>
              <p className="card-sub" style={{ marginBottom: 0 }}>
                Signed so positive means the joint ranking beats a random ordering of the same
                joints on the same model. Zero or negative is a real finding — the explanation
                looked plausible and did no work — not a failed run.
              </p>
            </div>
            <div className="glass pad">
              <h3 className="card-title">Why a baseline row</h3>
              <p className="card-sub" style={{ marginBottom: 0 }}>
                The baseline is the same architecture trained with a plain classification loss and
                evaluated through the same windowing and decision logic. Comparing against a
                published figure instead would confound the objective with a different evaluation
                protocol.
              </p>
            </div>
          </div>

          <div style={{ marginTop: 16 }}>
            <OperatingCurve />
          </div>

          <p className="card-sub" style={{ marginTop: 14 }}>
            Generated from the run directories by <code>scripts/export_results.py</code> and{" "}
            <code>scripts/export_curve.py</code> ·{" "}
            <span className="mono">{results.generated_utc}</span>
          </p>
        </>
      )}
    </section>
  );
}
